const path = require('node:path');
process.chdir(__dirname);

// This file is used for hosting providers (like Hostinger) that expect a server.js in the root.
// It requires the standalone server generated by Next.js during the build process.
// Note: You must run 'npm run build' first for this to work.

try {
  require('./.next/standalone/server.js');
} catch (error) {
  console.error("Error: Could not find .next/standalone/server.js. Did you run 'npm run build'?");
  process.exit(1);
}
